### PR TITLE
create release pipeline

### LINKED ISSUE #1: Release binaries for older machines
Looks very interesting, but it suffers from the common "requires a very recent GLIBC" issue. If you could release binaries that are made on an older machine, it would not affect people with a newer GLIBC, but it would extend your reach. I am on the latest Ubuntu-family LTS (20.04), but last month I was still running 18.04 and I ran into this issue a lot...
Debug output:
```
map2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by map2)
map2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by map2)
```

### PR DESCRIPTION
**Pull request by Inve1951**
Adds a GitHub workflow action that produces structurally identical output to the current release uploads.

It's manually triggered via `workflow_dispatch`. I.e. used like this:
1. Create and push a version tag.
2. Go to https://github.com/shiro/map2/actions/workflows/release.yml and run the pipeline
    image
3. When it finished successfully it will have created a draft release in the GitHub releases section.
4. Review / edit release notes and publish release.

glibc version: 2.31

Fixes #1

### CODE REVIEW

**Comment by shiro** [comment]
Thanks! Will check it out in a week or two when I find some time for it.
I also need to make sure it works on the `python` branch as the main one will be deprecates as per the notice at the beginning of the README.

I really appreciate the work, sorry for the delay.

**Comment by shiro** [comment]
The new major version of map2 is now available!

It also includes a build pipeline that runs integration tests, generates documentation and deploys to PyPI!  
I appreciate the effort on this PR, sorry it didn't get merged :bow: 

Feel free to open new issues for further CI improvement suggestions, etc. :rocket:

**Comment by shiro** [comment]
I'm less familiar with the whole python situation, please correct me if I'm wrong here...

`ubuntu-latest` is just the CI environment, it actually uses [manylinux](https://github.com/pypa/manylinux) through docker with the official PYO3 github action. This is the way most rust packages I looked at use and is recommended by PYO3 itself.

It should be using a much older ubuntu for building, did you make sure it doesn't work for you? (i.e. try installing through pip)

**Comment by Inve1951** [comment]
Oh, I was just clarifying. I'm also not familiar with the python setup but according to https://github.com/PyO3/maturin-action/blob/v1/src/index.ts#L27 it [should be fine](https://github.com/pypa/manylinux#readme). Haven't tested yet.

**Pull request closed without merging**
